### ISSUE TITLE
Front camera not working with GCam (but working with stock camera) on current kernel

### ISSUE THREAD

**Issue by Sqwalou** [crdroidandroid/android_kernel_xiaomi_mt6785#1]
Hello,
First of all, thank you for extending the life of this device!

I'm having an issue where the front camera of my begonia is causing any version of GCam to crash instantly on the current CrDroid kernel (although the stock camera works somehow).

From what I gathered, it's apparently due to Xiaomi having changed the front camera sensor on a later batch of RN8P to a Samsung ISOCell S5K3T1, which uses different drivers.

I have found that someone (MrErenk) made a kernel to support it, which I'm currently flashing after every CrDroid update, but ideally I'd love to be able to use the kernel you spend so much time on to optimize with CrDroid without having to replace it.
Do you think it would be possible to include support for that front sensor in your kernel?

For your reference, the XDA post about the working kernel can be found [here](https://forum.xda-developers.com/t/kernel-working-front-gcam-in-r-oss-builds.4551737/) and the developer's GitHub appears to be [this one](https://github.com/MrErenK/android_kernel_xiaomi_mt6785).

Thank you for your time and your hard work!

**Comment by gwolf2u** [comment]
closing this since GCam is not really focus of crDroid
anyway, @DarkJoker360 if you're willing to have a look, reopen please for tracking

**Comment by DarkJoker360** [comment]
Hello this has been addressed here: https://github.com/begonia-dev/android_kernel_xiaomi_mt6785/commit/cfb9a76b5a184f63c276a64497af455e02e5eacc

The fix will be available starting from next updates.

**Comment by Sqwalou** [comment]
Oh, thank you so much!

**Comment by Sqwalou** [comment]
It works after the latest update. Thank you again!
